version: "3.7"
services:
  postgres:
    container_name: 'postgres-ctn'
    image: 'postgres:11.2'
    restart: always
    ports:
      - '5433:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=to_do'
      - 'POSTGRES_PASSWORD=admin@123'
